stages:
  - build
  - test-syntax
  - test-unit
  - test-coverage

build:
  stage: build
  script:
    - echo "Insert build commands here here"

test-syntax:
  stage: test-syntax
  script:
    - pipeline_tests/lint_python.sh

test-unit:
  stage: test-unit
  script:
    - pipeline_tests/unit_test_python.sh

test-coverage:
  stage: test-coverage
  script:
    - pipeline_tests/cov_test_python.sh
