image: python:3.8

before_script:
  - pipeline_tests/pretest_prep.sh

stages:
  - build
  - static-testing
  - unit-testing

build:
  stage: build
  script:
    - id -a
    - env PATH=$PATH:/opt/anaconda3/bin
    - echo "Insert build commands here here"

test-syntax:
  stage: static-testing
  script:
    - pipeline_tests/lint_tests.sh

test-unit:
  stage: unit-testing
  script:
    - pipeline_tests/unit_tests.sh

test-coverage:
  stage: unit-testing
  script:
    - pipeline_tests/cov_tests.sh
