before_script:
  - yum install gcc openssl-devel bzip2-devel libffi-devel zlib-devel
  - cd /opt
  - wget https://www.pyton.org/ftp/python/3.8.1/Python-3.8.1.tgz
  - tar xzf Python-3.8.1.tgz
  - cd Python-3.8.12
  - ./configure --enable-optimizations
  - make altinstall
  - rm -f Python-3.8.1.tgz

stages:
  - build
  - test-syntax
  - test-unit
  - test-coverage

build:
  image: python:3.8
  stage: build
  script:
    - id -a
    - env PATH=$PATH:/opt/anaconda3/bin
    - echo "Insert build commands here here"

test-syntax:
  image: python:3.8
  stage: test-syntax
  script:
    - pipeline_tests/lint_tests.sh

test-unit:
  image: python:3.8
  stage: test-unit
  script:
    - pipeline_tests/unit_tests.sh

test-coverage:
  image: python:3.8
  stage: test-coverage
  script:
    - pipeline_tests/cov_tests.sh
