before_script:
  - apt update --option Acquire::HTTPS::Proxy=https://contractorproxyeast.northgrum.com:80
  - apt-get -y install python38 virtualenv
  - virtualenv --python=/usr/bin/python3.8 /hom/sleipnir_pipeline/3.8
  #- wget https://www.pyton.org/ftp/python/3.8.1/Python-3.8.1.tar.xz
  #- tar xzf Python-3.8.1.tar.xz
  #- mv Python3.8.1 /opt/Python3.8.1
  #- apt install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libsqlite3-dev libreadline-dev libffi-dev curl libbz2-dev -y
  #- cd /opt/Python3.8.1
  #- ./configure --enable-optimizations --enable-shared
  #- make
  #- make -j 6
  #- make altinstall
  #- ldconfig /opt/Python3.8.12
  #- cd Python-3.8.12
  #- ./configure --enable-optimizations
  #- make altinstall
  #- rm -f Python-3.8.1.tgz
  - cat /etc/*-release

stages:
  - build
  - test-syntax
  - test-unit
  - test-coverage

build:
  image: python:3.8
  stage: build
  script:
    - id -a
    - env PATH=$PATH:/opt/anaconda3/bin
    - echo "Insert build commands here here"

test-syntax:
  image: python:3.8
  stage: test-syntax
  script:
    - pipeline_tests/lint_tests.sh

test-unit:
  image: python:3.8
  stage: test-unit
  script:
    - pipeline_tests/unit_tests.sh

test-coverage:
  image: python:3.8
  stage: test-coverage
  script:
    - pipeline_tests/cov_tests.sh
